# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8383a132b5ca6d36a098f376fa817afe84bc1967e31c767dec1c0d5594672eb9434b7e990fff8bfcf6a937184c164425a7e3d9b0c2b4a5b6ea05f6a7bddbf35f

test:
  secret_key_base: f0f25485015d42d8d5f2ef17685cf7ad2ebf87ff2ac702c2721b3bd61f12f48d109903f393505a94be3dcccd505ed5201b2b1b37f15b3e86486ea94bec1a5f43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
